### ISSUE TITLE
ZeroDivisionError: Weights sum to zero, can't be normalized

### ISSUE THREAD

**Issue by BartWitjes** [MStarmans91/WORC#10]
When running the trainclassifier function, I ran into the following error:

>   File "C:\Users\Gebruiker\Anaconda3\envs\py27\lib\site-packages\PREDICT\processing\SearchCV.py", line 618, in _store
>     array_means[:, np.newaxis]) ** 2,
> 
> TypeError: list indices must be integers, not tuple

I tried removing `[:, np.newaxis]`, which resulted into the following error:

>   File "C:\Users\Gebruiker\Anaconda3\envs\py27\lib\site-packages\PREDICT\processing\SearchCV.py", line 619, in _store
>     axis=1, weights=weights))
> 
>   File "C:\Users\Gebruiker\Anaconda3\envs\py27\lib\site-packages\numpy\lib\function_base.py", line 386, in average
>     "Weights sum to zero, can't be normalized")
> 
> ZeroDivisionError: Weights sum to zero, can't be normalized

So I'm getting zeros in my test_scores, is the problem within my data, or can't I just remove `[:, np.newaxis]`?

(btw, line 611 in Search_CV has a '{' too many.)

**Comment by MStarmans91** [comment]
Do you get the warning from line 612, just before this error? I guess so, that's why you noticed the extra } (which I now removed). Indeed, you get a zero division error as all your scores are zero for a specific metric. I tried to solve this error in line 613, but it seems I did that incorrectly as I created the array_means as a list and not an array.

Can you replace line 613 with the following in order to make it an array:
```
array_means = np.asarray([0] * array.shape[1])
```
and let me know if that solves the issue? You should leave the ```[:, np.newaxis]``` in line 618.

**Comment by BartWitjes** [comment]
Thanks, indeed I get the warning from line 612. 

I recplaced line 613, this resulted in a new error:

>   File "C:\Users\Gebruiker\Anaconda3\envs\py27\lib\site-packages\PREDICT\processing\SearchCV.py", line 618, in _store
>     array_means[:, np.newaxis]) ** 2,
> 
> ValueError: operands could not be broadcast together with shapes (10000,5) (5,1)

**Comment by MStarmans91** [comment]
I guess I'm taking the wrong shape dimension: should be the zeroth looking at your result. Can you try instead ```array_means = np.asarray([0] * array.shape[0])```?

**Comment by BartWitjes** [comment]
Now I get the old error again (`ZeroDivisionError: Weights sum to zero, can't be normalized`)

**Comment by MStarmans91** [comment]
On a sidenote: which is the first line in the SearchCV which gives the error: 632? 

In this part, we compute the average and std for several performance metrics over all folds in thetrain/validation cross validation. For the test score, we take a weighted average; the weights are the number of samples in the test set, as this is not necessarily the same for all folds. Your weights sum to zero, which is why the weighted average is not working.

That in itself seems odd, as that would suggest there are no samples in the validation set. Can you print the test_sample_counts before line 632 to check this? This is the real issue which we would have to solve, as this seems implausible.

If the weights sum to zero, in line 613 we make an exception by simply setting the averages to zero. We would have to make a similar exception for the stds in order to make it work. But now that I think of it, it would be better to try and take the unweighted average instead of setting sit to zeros.

Can you replace the whole store function by the following:

```
        def _store(key_name, array, weights=None, splits=False, rank=False):
            """A small helper to store the scores/times to the cv_results_"""
            array = np.array(array, dtype=np.float64).reshape(n_candidates,
                                                              n_splits)
            if splits:
                for split_i in range(n_splits):
                    results["split%d_%s"
                            % (split_i, key_name)] = array[:, split_i]

            try:
                array_means = np.average(array, axis=1, weights=weights)
            except ZeroDivisionError as e:
                e = ('[PREDICT Warning] {}. Setting {} to unweighted.').format(e, key_name)
                print(e)
                array_means = np.average(array, axis=1)

            results['mean_%s' % key_name] = array_means
            # Weighted std is not directly available in numpy
            try:
                array_stds = np.sqrt(np.average((array -
                                                 array_means[:, np.newaxis]) ** 2,
                                                axis=1, weights=weights))
            except ZeroDivisionError as e:
                e = ('[PREDICT Warning] {}. Setting {} to unweighted.').format(e, key_name)
                print(e)
                array_stds = np.sqrt(np.average((array -
                                                 array_means[:, np.newaxis]) ** 2,
                                                axis=1))

            results['std_%s' % key_name] = array_stds

            if rank:
                results["rank_%s" % key_name] = np.asarray(
                    rankdata(-array_means, method='min'), dtype=np.int32)
```

**Comment by BartWitjes** [comment]
The first line which gives the error is 619, this is the complete error code:

```
File "<ipython-input-1-712787033c31>", line 17, in <module>
    trainclassifier.trainclassifier(test, patientinfo, config, output_hdf, output_json)

  File "C:\Users\Gebruiker\Anaconda3\envs\py27\lib\site-packages\PREDICT\trainclassifier.py", line 226, in trainclassifier
    tempsave=config['General']['tempsave'])

  File "C:\Users\Gebruiker\Anaconda3\envs\py27\lib\site-packages\PREDICT\classification\crossval.py", line 295, in crossval
    **config['HyperOptimization'])

  File "C:\Users\Gebruiker\Anaconda3\envs\py27\lib\site-packages\PREDICT\classification\parameter_optimization.py", line 81, in random_search_parameters
    random_search.fit(features, labels)

  File "C:\Users\Gebruiker\Anaconda3\envs\py27\lib\site-packages\PREDICT\processing\SearchCV.py", line 1630, in fit
    return self._fit(X, y, groups, sampled_params)

  File "C:\Users\Gebruiker\Anaconda3\envs\py27\lib\site-packages\PREDICT\processing\SearchCV.py", line 1385, in _fit
    X=X, y=y)

  File "C:\Users\Gebruiker\Anaconda3\envs\py27\lib\site-packages\PREDICT\processing\SearchCV.py", line 627, in process_fit
    weights=test_sample_counts if self.iid else None)

  File "C:\Users\Gebruiker\Anaconda3\envs\py27\lib\site-packages\PREDICT\processing\SearchCV.py", line 619, in _store
    axis=1, weights=weights))

  File "C:\Users\Gebruiker\Anaconda3\envs\py27\lib\site-packages\numpy\lib\function_base.py", line 386, in average
    "Weights sum to zero, can't be normalized")

ZeroDivisionError: Weights sum to zero, can't be normalized
```
I printed the test_sample_count before the store function, which resulted in:
` TEST SAMPLE COUNTS: [0 0 0 0 0]`

I replaced the store function with your code. It does get past the previous error, but something goes wrong later, I think still because the weights are 0:

```
  File "C:\Users\Gebruiker\Anaconda3\envs\py27\lib\site-packages\sklearn\utils\validation.py", line 590, in check_array
    context))

ValueError: Found array with 0 feature(s) (shape=(44, 0)) while a minimum of 1 is required.

```
I attached more lines of the log:
[testclassifier.txt](https://github.com/MStarmans91/WORC/files/3053601/testclassifier.txt)
.

**Comment by MStarmans91** [comment]
In the log, you can see that the best hyperparameter setting in your search was one in which the number of features after feature selection is 0. That seems odd, but I think I know what the issue is. You are using the groupwise feature selection, which selects features based on their name or label. This only works when you extracted features with PREDICT, as we use those label names. I know that you input your own features, so you should not use this.

In order to solve this, in your config, in WORC>=2.1.2, set:
``` config['Featsel']['GroupwiseSearch'] = 'False' ```

In WORC < 2.1.2, set:
```config['General']['FeatureCalculator'] ``` to any string not including PREDICT.

Just to be sure, I would do both :).

Some background on why this specifically occurs in PREDICT. Normally, using zero features for an estimator would give an error in the sklearn _fit_and_score function, see PREDICT.processing.fitandscore, line 644. If you do feature selection, this could occasionally happen when selecting bad hyperparameters, which would than trow an error. In order to prevent this, when the number of selected features is zero before calling this function, we output a dummy object with only zeros. As this normally only occurs seldom, it's not an issue. However, since in your case this always happens, it became an issue. I will try to create a better error message for this.

**Comment by BartWitjes** [comment]
Thanks, this indeed solves the issue! Thank you for the explanation!
