### ISSUE TITLE
Labeling Issue - No entry found

### ISSUE THREAD

**Issue by auxiliumx** [MStarmans91/WORC#13]
I've got an issue in which the classify_all job fails. Manually running the call command raises the following error:
`PREDICT.addexceptions.PREDICTIOError: No entry found in labeling for feature file c:\users\oliver\appdata\local\temp\LiTS_Classification\calcfeatures_train_CT_0\id_0\features_0.hdf5.
`
It looks like an issue of loading the correct labels within PREDICT\trainclassifier.py . However, I double check the pinfo.txt file containg the labels. It has the same format as the tutorial example (separation with spaces) and contains the headers 'Patient' and 'Label1' of which the latter is also correct in the config.genetics.
The PatientID's correspond with the foldernames containing the image.nii.gz and mask.nii.gz .
What have I missed? 

The patient_info_file used: [pinfo_small.txt](https://github.com/MStarmans91/WORC/files/3084885/pinfo_small.txt)

**Comment by MStarmans91** [comment]
The issue is not in the label file: the format seems correct. In this piece of code we try to find the label  belonging to each feature file. Hence we match the ``patient'' names from the label file to the feature file. This is not so sophisticated: we simply look whether any of the patient names from your label file occur in the feature files.

In this instance, that's not the case. Your patient ID's in the label file are 
```
patch0
patch1
patch2
patch3
patch4
patch5
patch3132
patch3133
patch3134
patch3135
patch3136
patch3137
```

Indeed, none of these occur in the feature file name.

Normally, we fix this by using the patient names as sample ID's, e.g. instead of the ```id_0``` in your file name this would have been say ```patch0```. ```WORC``` will use the same sample ID's for the features as for the images on which they were computed. If you do not supply sample ID's, ```fastr``` will create default IDs like ```id_0```, which is the case in your workflow.

I assume you supplied your images as a list? If you do that, these automatic default sample ID's will be used.  If you supply them as a dictionary instead, the keys will be used as sample ID's, the values should be the filenames. 

So, you could either rename the feature files or rerun WORC supplying the images as a dictionary, assuming you haven't done that.

**Comment by auxiliumx** [comment]
The dictionary fixed it! Thanks!
`image_sources = {os.path.basename(os.path.dirname(i)): i for i in image_sources}`
