### ISSUE TITLE
trainclassifier error

### ISSUE THREAD

**Issue by BartWitjes** [MStarmans91/WORC#8]
When I tried to run the trainclassifier, I ran into this error:

> File "<ipython-input-36-fc2ba9ee56a1>", line 1, in <module>
>     trainclassifier.trainclassifier(test, patientinfo, config, output_hdf, output_json)
> 
>   File "C:\Users\Gebruiker\Anaconda3\envs\py27\lib\site-packages\PREDICT\trainclassifier.py", line 226, in trainclassifier
>     tempsave=config['General']['tempsave'])
> 
>   File "C:\Users\Gebruiker\Anaconda3\envs\py27\lib\site-packages\PREDICT\classification\crossval.py", line 295, in crossval
>     **config['HyperOptimization'])
> 
>   File "C:\Users\Gebruiker\Anaconda3\envs\py27\lib\site-packages\PREDICT\classification\parameter_optimization.py", line 80, in random_search_parameters
>     verbose=1, cv=cv)
> 
> TypeError: __init__() takes at least 2 arguments (7 given)

I tried changing the tempsave and hyperoptimization parameters in the config file, but that didn't change anything.

**Comment by MStarmans91** [comment]
Apparently, there is a bug in the RandomizedSearchCVJoblib in PREDICT 2.1.2 which causes this error. I will solve it asap and make a new release. 

For now, as an alternative, you can use the RandomizedSearchCVfastr instead, which instead of Joblib uses fastr to run the hyperparameter optimization in parallel. To do so, set the config['Classification']['fastr']  field to 'True'.

**Comment by BartWitjes** [comment]
Thanks!
