### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jonasboh** [MStarmans91/WORC#82]
**Describe the bug**
After pip install WORC all libs like scikit-learn and imbalanced-learn are downgraded to versions which have conflicts with other libraries. I get the following error when importing WORC: 

[WARNING]  __init__:0082 >> Not running in a production installation (branch "unknown" from installed package)
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

Downgrading numpy to version 1.19 gives additional problems with matplotlib.
Seems like dependencies here are not up to date.

**WORC configuration**
Not any changes applied.

**To Reproduce**
pip install worc==3.6.0
python
import WORC

**Desktop:**
 - OS: [Ubuntu Linux]
 - Python version: [3.9.15]
 - WORC Version [3.6.0]

**Comment by MStarmans91** [comment]
Note that due to some dependencies, e.g. pyradiomics, WORC currently requires Python 3.6 or 3.7. I see you are using Python 3.9.15, that might cause some issues. when using Python 3.7, I don't run into any issues, since the versions of some packages including numpy that still support Python 3.7 are older. For numpy, I have tried up till 1.19.5. I hope in the near future WORC can support more recent Python versions, as 3.7 is quite old.

Please let me know whether the issue persists when downgrading to Python 3.7.

**Comment by MStarmans91** [comment]
Closed due to inactivity, feel free to reopen if the issue persists
